swagger: '2.0'
info:
  version: '1.1'
  title: "ProximaCityAirAPI"
  description: This is a simple API that shows how to expose Air Condition Data
              as read from the Aircare device
              It is part of the ProximaCityDemo
  contact:
    name: Oracle Innovation Team Italy
    email: luigi.saetta@oracle.com
    url: https://www.facebook.com/Oracle-Innovation-Team-Italia-1277459822387467/
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
host: polls.apiblueprint.org
basePath: /proximacityair
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /measurements:
    get:
      operationId: findMeasures
      summary: List all latest measurements of Air conditions
      parameters:
        - name: device_id
          in: query
          description: the id of the device (id_list))
          required: true
          type: integer
          format: int32
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/Measure'
          examples:
            application/json:
              - id: 12346
                ts_op: 1234567891
                lux: 300
                temp: 23.6
                humidity: 49.7
                pressure: 1008.6
                iaq: 100
                tvoc: 7
                co2e: 400
                pm2_5: 6
                pm10: 10
                hflevel: 0.9
                lflevel: 200
              - id: 12345
                ts_op: 1234567890
                lux: 301
                temp: 23.7
                humidity: 49.7
                pressure: 1008.6
                iaq: 104
                tvoc: 7
                co2e: 400
                pm2_5: 6
                pm10: 10
                hflevel: 0.9
                lflevel: 200
              - id: 12344
                ts_op: 1234567889
                lux: 306
                temp: 23.7
                humidity: 49.8
                pressure: 1008.7
                iaq: 104
                tvoc: 7
                co2e: 400
                pm2_5: 6
                pm10: 10
                hflevel: 0.9
                lflevel: 200
  /measurements/last:
    get:
      operationId: findMeasure
      summary: retrieve the last measure of Air Conditions
      parameters:
        - name: device_id
          in: query
          description: the id of the device (id_list)
          required: true
          type: integer
          format: int32
      responses:
        200:
          description: Successful Response
          schema:
            $ref: '#/definitions/Measure'
          examples:
            application/json:
                - id: 12346
                  ts_op: 1234567891
                  lux: 300
                  temp: 23.6
                  humidity: 49.7
                  pressure: 1008.6
                  iaq: 100
                  tvoc: 7
                  co2e: 400
                  pm2_5: 6
                  pm10: 10
                  hflevel: 0.9
                  lflevel: 200
definitions:
  Measure:
    title: Measure
    type: object
    properties:
      id:
        type: number
      ts_op:
        type: number
        format: int64
      lux:
        type: number
      temp:
        type: number
        format: float
      humidity:
        type: number
        format: float
      pressure:
        type: number
        format: float
      iaq:
        type: number
      tvoc:
        type: number
      co2e:
        type: number
      pm2_5:
        type: number
      pm10:
        type: number
      hflevel:
        type: number
        format: float
      lflevel:
        type: number